[project]
name = "programming-for-ds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shaheer4290", email = "syedshaheer4290@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
    "seaborn>=0.13.2",
]

[project.scripts]
programming-for-ds = "programming_for_ds:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
